# see https://github.com/symfony/recipes/blob/master/symfony/security-bundle/3.3/config/packages/security.yaml
security:
    encoders:
        MsgPhp\User\Infrastructure\Security\UserIdentity: auto
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
            chain:
                providers: [msgphp_user, msgphp_user_jwt]
        msgphp_user: { id: MsgPhp\User\Infrastructure\Security\UserIdentityProvider }
        msgphp_user_jwt: { id: MsgPhp\User\Infrastructure\Security\Jwt\UserIdentityProvider }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_login:
            pattern: ^/api/login
            anonymous: true
            stateless: true
            provider: chain_provider
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api_register:
            pattern: ^/api/register
            anonymous: true
            stateless: true
            provider: chain_provider
        
        api_reset_password:
            pattern: ^/api/reset-password
            anonymous: true
            stateless: true
            provider: chain_provider

        api:
            pattern: ^/api
            anonymous: true
            stateless: true
            provider: chain_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main_admin:
            pattern: ^/admin
            anonymous: true
            provider: chain_provider
            form_login:
                login_path: /
                check_path: login
                default_target_path: home
                username_parameter: email
                password_parameter: password
            logout:
                path: app_logout
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        html_proxy:
            pattern: ^/
            security: false

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
